PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX toezicht: <http://mu.semte.ch/vocabularies/ext/supervision/>

DELETE {
  GRAPH <http://mu.semte.ch/graphs/organizations/141d9d6b-54af-4d17-b313-8d1c30bc3f5b> {
  ?s ?p ?o.
  }
}

WHERE {
  GRAPH <http://mu.semte.ch/graphs/organizations/141d9d6b-54af-4d17-b313-8d1c30bc3f5b> {

    ?s a  ?type.
    FILTER (?type IN (toezicht:DecisionType, toezicht:RegulationType ) ).
    ?s ?p ?o.
 }
}
