DELETE {
  GRAPH ?g {
    ?s ?p ?o .
  }  
} WHERE {
  GRAPH ?g {
    ?s a <http://mu.semte.ch/vocabularies/ext/Permission> ; ?p ?o .
  }
}

;

DELETE {
  GRAPH ?g {
    ?s ?p ?o .
  }  
} WHERE {
  GRAPH ?g {
    ?s a <http://xmlns.com/foaf/0.1/OnlineAccount> ; ?p ?o .
  }
}
 

