PREFIX toezicht: <http://mu.semte.ch/vocabularies/ext/supervision/>
PREFIX adms: <http://www.w3.org/ns/adms#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dct: <http://purl.org/dc/terms/>

DELETE {
  GRAPH <http://mu.semte.ch/graphs/organizations/141d9d6b-54af-4d17-b313-8d1c30bc3f5b> {
    ?inzendingVoorToezichtMelding adms:status ?meldingStatus .
  }
}
INSERT {
  GRAPH <http://mu.semte.ch/graphs/organizations/141d9d6b-54af-4d17-b313-8d1c30bc3f5b> {
    ?inzendingVoorToezichtMelding adms:status <http://data.lblod.info/melding-statuses/afgehandeld> .
  }

}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/organizations/141d9d6b-54af-4d17-b313-8d1c30bc3f5b> {
    ?inzendingVoorToezichtMelding a toezicht:InzendingVoorToezichtMelding .
    ?inzendingVoorToezichtMelding dct:subject ?inzendingVoorToezicht .
    ?inzendingVoorToezicht dct:created ?created .
    ?inzendingVoorToezichtMelding adms:status ?meldingStatus .
  }
  FILTER (?created < "2019-01-03T00:00:00"^^xsd:dateTime)
}
