PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>

DELETE {
  GRAPH <http://mu.semte.ch/graphs/organizations/141d9d6b-54af-4d17-b313-8d1c30bc3f5b> {
    ?w ext:inProvincie ?wprov .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/organizations/141d9d6b-54af-4d17-b313-8d1c30bc3f5b> {
    ?w ext:inProvincie ?prov .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/organizations/141d9d6b-54af-4d17-b313-8d1c30bc3f5b> {
    ?s ext:inProvincie ?prov ; <http://data.vlaanderen.be/ns/besluit#werkingsgebied> ?w .
    ?w ext:inProvincie ?wprov .

    VALUES ?s {
      <http://data.lblod.info/id/bestuurseenheden/ff7d80dc-ec00-43ac-ac7e-d51694df37ff>
    }
  }
}
