DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/141d9d6b-54af-4d17-b313-8d1c30bc3f5b> {
    <http://data.lblod.info/DecisionType/3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8> a <http://mu.semte.ch/vocabularies/ext/supervision/DecisionType> .
    <http://data.lblod.info/DecisionType/3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8> <http://mu.semte.ch/vocabularies/core/uuid> "3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8" .
    <http://data.lblod.info/DecisionType/3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8> <http://www.w3.org/2004/02/skos/core#prefLabel> "Rechtspositieregeling" .
  }
}
;
DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/141d9d6b-54af-4d17-b313-8d1c30bc3f5b> {
    <http://data.lblod.info/inzendingen-voor-toezicht/5C18D5B898360D00090004BB> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5C18D60F98360D00090004BF> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5C08F81398360D00090003A7> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5C18E2EB98360D00090004CB> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5C18E33098360D00090004CD> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5C51649DD5BECA00090000CF> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5BC742CD98360D0009000354> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5BAB4BEB98360D00090000F0> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5BB22DC298360D000900030B> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5C091EC598360D0009000403> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5C18D7BA98360D00090004C1> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5C2DB84C9E5B640009000089> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5BA2193C98360D00090000DC> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5C0F995998360D0009000090> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8> .
  }
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/inzendingen-voor-toezicht/5C18D5B898360D00090004BB> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5C18D60F98360D00090004BF> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5C08F81398360D00090003A7> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5C18E2EB98360D00090004CB> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5C18E33098360D00090004CD> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5C51649DD5BECA00090000CF> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5BC742CD98360D0009000354> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5BAB4BEB98360D00090000F0> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5C091EC598360D0009000403> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5BB22DC298360D000900030B> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5C18D7BA98360D00090004C1> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5C2DB84C9E5B640009000089> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5BA2193C98360D00090000DC> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5C0F995998360D0009000090> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8> .
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/141d9d6b-54af-4d17-b313-8d1c30bc3f5b> {
    <http://data.lblod.info/inzendingen-voor-toezicht/5C18D5B898360D00090004BB> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/02e210746b795a80ec114d09d5f372cd77be01b5f813776e09409c6044d39ef6> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5C18D60F98360D00090004BF> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/02e210746b795a80ec114d09d5f372cd77be01b5f813776e09409c6044d39ef6> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5C08F81398360D00090003A7> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/02e210746b795a80ec114d09d5f372cd77be01b5f813776e09409c6044d39ef6> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5C18E2EB98360D00090004CB> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/02e210746b795a80ec114d09d5f372cd77be01b5f813776e09409c6044d39ef6> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5C18E33098360D00090004CD> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/02e210746b795a80ec114d09d5f372cd77be01b5f813776e09409c6044d39ef6> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5C51649DD5BECA00090000CF> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/02e210746b795a80ec114d09d5f372cd77be01b5f813776e09409c6044d39ef6> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5BC742CD98360D0009000354> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/02e210746b795a80ec114d09d5f372cd77be01b5f813776e09409c6044d39ef6> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5BAB4BEB98360D00090000F0> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/02e210746b795a80ec114d09d5f372cd77be01b5f813776e09409c6044d39ef6> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5BB22DC298360D000900030B> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/02e210746b795a80ec114d09d5f372cd77be01b5f813776e09409c6044d39ef6> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5C091EC598360D0009000403> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/02e210746b795a80ec114d09d5f372cd77be01b5f813776e09409c6044d39ef6> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5C18D7BA98360D00090004C1> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/02e210746b795a80ec114d09d5f372cd77be01b5f813776e09409c6044d39ef6> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5C2DB84C9E5B640009000089> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/02e210746b795a80ec114d09d5f372cd77be01b5f813776e09409c6044d39ef6> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5BA2193C98360D00090000DC> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/02e210746b795a80ec114d09d5f372cd77be01b5f813776e09409c6044d39ef6> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5C0F995998360D0009000090> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/02e210746b795a80ec114d09d5f372cd77be01b5f813776e09409c6044d39ef6> .
  }
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/inzendingen-voor-toezicht/5C18D5B898360D00090004BB> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/02e210746b795a80ec114d09d5f372cd77be01b5f813776e09409c6044d39ef6> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5C18D60F98360D00090004BF> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/02e210746b795a80ec114d09d5f372cd77be01b5f813776e09409c6044d39ef6> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5C08F81398360D00090003A7> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/02e210746b795a80ec114d09d5f372cd77be01b5f813776e09409c6044d39ef6> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5C18E2EB98360D00090004CB> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/02e210746b795a80ec114d09d5f372cd77be01b5f813776e09409c6044d39ef6> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5C18E33098360D00090004CD> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/02e210746b795a80ec114d09d5f372cd77be01b5f813776e09409c6044d39ef6> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5C51649DD5BECA00090000CF> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/02e210746b795a80ec114d09d5f372cd77be01b5f813776e09409c6044d39ef6> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5BC742CD98360D0009000354> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/02e210746b795a80ec114d09d5f372cd77be01b5f813776e09409c6044d39ef6> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5BAB4BEB98360D00090000F0> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/02e210746b795a80ec114d09d5f372cd77be01b5f813776e09409c6044d39ef6> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5BB22DC298360D000900030B> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/02e210746b795a80ec114d09d5f372cd77be01b5f813776e09409c6044d39ef6> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5C091EC598360D0009000403> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/02e210746b795a80ec114d09d5f372cd77be01b5f813776e09409c6044d39ef6> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5C18D7BA98360D00090004C1> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/02e210746b795a80ec114d09d5f372cd77be01b5f813776e09409c6044d39ef6> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5C2DB84C9E5B640009000089> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/02e210746b795a80ec114d09d5f372cd77be01b5f813776e09409c6044d39ef6> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5BA2193C98360D00090000DC> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/02e210746b795a80ec114d09d5f372cd77be01b5f813776e09409c6044d39ef6> .
    <http://data.lblod.info/inzendingen-voor-toezicht/5C0F995998360D0009000090> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/02e210746b795a80ec114d09d5f372cd77be01b5f813776e09409c6044d39ef6> .
  }
}
