DELETE {
  GRAPH ?g {
   	<http://data.lblod.info/id/bestuurseenheden/5567394c206a8da9fe1e8ab4dc1d043eabdb5915ecf3d06a9495dc64cc3c691e> <http://mu.semte.ch/vocabularies/ext/inProvincie> <http://data.lblod.info/id/werkingsgebieden/f2bda6eb42c1ab85c4ef36588a043ac2bfeffa31bfb88bb7abc597f01efe270b> .
  }
}
WHERE {
  GRAPH ?g {
     	<http://data.lblod.info/id/bestuurseenheden/5567394c206a8da9fe1e8ab4dc1d043eabdb5915ecf3d06a9495dc64cc3c691e> <http://mu.semte.ch/vocabularies/ext/inProvincie> <http://data.lblod.info/id/werkingsgebieden/f2bda6eb42c1ab85c4ef36588a043ac2bfeffa31bfb88bb7abc597f01efe270b> .
  }
}
