DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/141d9d6b-54af-4d17-b313-8d1c30bc3f5b> {
    <http://data.lblod.info/id/bestuurseenheden/e45e6ad275ae04001029796b3771fa418b32414269ee741a5cf120a580ff673b> <http://www.w3.org/2004/02/skos/core#prefLabel> "AUTONOOM GEMEENTEBEDRIJF OPGLABBEEK" .
  }
}