# Can take a while to process
DELETE {
  GRAPH ?g {
    ?s ?p ?o .
  }
}
WHERE {
    {
    SELECT DISTINCT ?g
      WHERE {
        GRAPH ?g {
          ?s a <http://mu.semte.ch/vocabularies/ext/supervision/InzendingVoorToezicht> . # The magical property available in every temp graph.
        }
        FILTER regex(str(?g), "http://data.lblod.info/temp")
      }
    }
  GRAPH ?g {
    ?s ?p ?o .
  }
}