DELETE {
  GRAPH ?g {
    <http://data.lblod.info/DecisionType/9fb28f4a126a4f02940408344c37b81c32f567c30a7b0390dee14e8ead197b64> <http://www.w3.org/2004/02/skos/core#prefLabel> "Verslag lokale berokkenheid eredienstbesturen" .
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/DecisionType/9fb28f4a126a4f02940408344c37b81c32f567c30a7b0390dee14e8ead197b64> <http://www.w3.org/2004/02/skos/core#prefLabel> "Verslag lokale betrokkenheid eredienstbesturen" .
  }
}
WHERE {
  GRAPH ?g {
    <http://data.lblod.info/DecisionType/9fb28f4a126a4f02940408344c37b81c32f567c30a7b0390dee14e8ead197b64> <http://www.w3.org/2004/02/skos/core#prefLabel> "Verslag lokale berokkenheid eredienstbesturen" .
  }
};
