PREFIX toezicht: <http://mu.semte.ch/vocabularies/ext/supervision/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>

DELETE WHERE {
GRAPH <http://mu.semte.ch/graphs/organizations/141d9d6b-54af-4d17-b313-8d1c30bc3f5b> {
 ?subject a toezicht:InzendingVoorToezicht ;
    ?predicate ?object .
 FILTER(?predicate NOT IN (rdf:type, mu:uuid))
 }
}
